twist_mux:
  ros__parameters:
    topics:
      gamepad:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 10
      keyboard:
        topic: /cmd_vel_keyboard
        timeout: 0.5
        priority: 5
      emergency:
        topic: /cmd_vel_emergency
        timeout: 1.0
        priority: 100
    locks:
      emergency_stop:
        topic: /emergency_stop
        timeout: 0.0
        priority: 255
