/twist_mux:
  ros__parameters:
    topics:
      joy:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 10
        twist:
          linear:
            x: [-2.0, 2.0]
            y: [0.0, 0.0]
            z: [0.0, 0.0]
          angular:
            x: [0.0, 0.0]
            y: [0.0, 0.0]
            z: [-2.0, 2.0]
      keyboard:
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 5
        twist:
          linear:
            x: [-1.0, 1.0]
            y: [0.0, 0.0]
            z: [0.0, 0.0]
          angular:
            x: [0.0, 0.0]
            y: [0.0, 0.0]
            z: [-1.0, 1.0]
    locks:
      emergency_stop:
        topic: emergency_stop
        timeout: 0.0
        priority: 255
